env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - standard-with-typescript
  - plugin:react-hooks/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}


settings:
  react:
    version: '18'
